// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCommand(arg1) {
  return window['go']['main']['App']['AddCommand'](arg1);
}

export function AddDraftComment(arg1) {
  return window['go']['main']['App']['AddDraftComment'](arg1);
}

export function AddIgnoredCommenter(arg1) {
  return window['go']['main']['App']['AddIgnoredCommenter'](arg1);
}

export function CancelRun(arg1) {
  return window['go']['main']['App']['CancelRun'](arg1);
}

export function CommitSuggestion(arg1, arg2) {
  return window['go']['main']['App']['CommitSuggestion'](arg1, arg2);
}

export function DiscardPendingReview() {
  return window['go']['main']['App']['DiscardPendingReview']();
}

export function GetAuthState() {
  return window['go']['main']['App']['GetAuthState']();
}

export function GetCommands() {
  return window['go']['main']['App']['GetCommands']();
}

export function GetCommentThreads(arg1) {
  return window['go']['main']['App']['GetCommentThreads'](arg1);
}

export function GetDefaultCommandID() {
  return window['go']['main']['App']['GetDefaultCommandID']();
}

export function GetFileDiff(arg1) {
  return window['go']['main']['App']['GetFileDiff'](arg1);
}

export function GetIgnoredCommenters() {
  return window['go']['main']['App']['GetIgnoredCommenters']();
}

export function GetPRFiles() {
  return window['go']['main']['App']['GetPRFiles']();
}

export function GetPRLocalPath() {
  return window['go']['main']['App']['GetPRLocalPath']();
}

export function GetPendingReview() {
  return window['go']['main']['App']['GetPendingReview']();
}

export function GetThread(arg1) {
  return window['go']['main']['App']['GetThread'](arg1);
}

export function ListOpenPRs(arg1) {
  return window['go']['main']['App']['ListOpenPRs'](arg1);
}

export function LoadPullRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoadPullRequest'](arg1, arg2, arg3);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenFolderPicker(arg1, arg2) {
  return window['go']['main']['App']['OpenFolderPicker'](arg1, arg2);
}

export function PollDeviceFlow() {
  return window['go']['main']['App']['PollDeviceFlow']();
}

export function PostImmediateComment(arg1) {
  return window['go']['main']['App']['PostImmediateComment'](arg1);
}

export function RemoveCommand(arg1) {
  return window['go']['main']['App']['RemoveCommand'](arg1);
}

export function RemoveIgnoredCommenter(arg1) {
  return window['go']['main']['App']['RemoveIgnoredCommenter'](arg1);
}

export function ReplyToComment(arg1, arg2) {
  return window['go']['main']['App']['ReplyToComment'](arg1, arg2);
}

export function ResolveThread(arg1) {
  return window['go']['main']['App']['ResolveThread'](arg1);
}

export function RunCommands(arg1, arg2) {
  return window['go']['main']['App']['RunCommands'](arg1, arg2);
}

export function SetDefaultCommandID(arg1) {
  return window['go']['main']['App']['SetDefaultCommandID'](arg1);
}

export function SetPRLocalPath(arg1) {
  return window['go']['main']['App']['SetPRLocalPath'](arg1);
}

export function StartDeviceFlow() {
  return window['go']['main']['App']['StartDeviceFlow']();
}

export function SubmitReview(arg1) {
  return window['go']['main']['App']['SubmitReview'](arg1);
}

export function SyncPendingReview() {
  return window['go']['main']['App']['SyncPendingReview']();
}

export function UnresolveThread(arg1) {
  return window['go']['main']['App']['UnresolveThread'](arg1);
}
