// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetAuthState():Promise<model.AuthState>;

export function ListOpenPRs(arg1:model.PRListFilters):Promise<model.PRListResult>;

export function Logout():Promise<void>;

export function PollDeviceFlow():Promise<model.PollResult>;

export function StartDeviceFlow():Promise<model.DeviceFlowInfo>;
