// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAuthState() {
  return window['go']['main']['App']['GetAuthState']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function PollDeviceFlow() {
  return window['go']['main']['App']['PollDeviceFlow']();
}

export function StartDeviceFlow() {
  return window['go']['main']['App']['StartDeviceFlow']();
}
