// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddCommand(arg1:model.CommandDTO):Promise<Array<model.CommandDTO>>;

export function AddDraftComment(arg1:model.DraftCommentDTO):Promise<model.PendingReviewDTO>;

export function AddIgnoredCommenter(arg1:string):Promise<void>;

export function CancelRun(arg1:string):Promise<void>;

export function CommitSuggestion(arg1:number,arg2:string):Promise<model.SuggestionCommitResult>;

export function DiscardPendingReview():Promise<void>;

export function GetAuthState():Promise<model.AuthState>;

export function GetCommands():Promise<Array<model.CommandDTO>>;

export function GetCommentThreads(arg1:boolean):Promise<Array<model.CommentThreadDTO>>;

export function GetDefaultCommandName():Promise<string>;

export function GetFileDiff(arg1:string):Promise<model.ParsedDiffDTO>;

export function GetIgnoredCommenters():Promise<Array<model.IgnoredCommenterDTO>>;

export function GetPRFiles():Promise<Array<model.PRFileDTO>>;

export function GetPRLocalPath(arg1:string,arg2:string,arg3:number):Promise<string>;

export function GetPendingReview():Promise<model.PendingReviewDTO>;

export function GetThread(arg1:number):Promise<model.CommentThreadDTO>;

export function ListOpenPRs(arg1:model.PRListFilters):Promise<model.PRListResult>;

export function LoadPullRequest(arg1:string,arg2:string,arg3:number):Promise<model.PullRequestSummary>;

export function Logout():Promise<void>;

export function OpenFolderPicker(arg1:string,arg2:string):Promise<string>;

export function PollDeviceFlow():Promise<model.PollResult>;

export function PostImmediateComment(arg1:model.DraftCommentDTO):Promise<model.CommentDTO>;

export function RemoveCommand(arg1:string):Promise<Array<model.CommandDTO>>;

export function RemoveIgnoredCommenter(arg1:string):Promise<void>;

export function ReplyToComment(arg1:number,arg2:string):Promise<model.CommentDTO>;

export function ResolveThread(arg1:number):Promise<void>;

export function RunCommands(arg1:Array<string>,arg2:string,arg3:model.RunContext):Promise<Array<model.RunResult>>;

export function SetDefaultCommandName(arg1:string):Promise<void>;

export function SetPRLocalPath(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function StartDeviceFlow():Promise<model.DeviceFlowInfo>;

export function SubmitReview(arg1:model.ReviewSubmitDTO):Promise<model.ReviewSubmitResult>;

export function SyncPendingReview():Promise<model.PendingReviewDTO>;

export function UnresolveThread(arg1:number):Promise<void>;
