// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getPRState = `-- name: GetPRState :one
SELECT owner, repo, number, local_path
FROM pr_state
WHERE owner = ? AND repo = ? AND number = ?
`

type GetPRStateParams struct {
	Owner  string
	Repo   string
	Number int64
}

func (q *Queries) GetPRState(ctx context.Context, arg GetPRStateParams) (PrState, error) {
	row := q.db.QueryRowContext(ctx, getPRState, arg.Owner, arg.Repo, arg.Number)
	var i PrState
	err := row.Scan(
		&i.Owner,
		&i.Repo,
		&i.Number,
		&i.LocalPath,
	)
	return i, err
}

const upsertPRLocalPath = `-- name: UpsertPRLocalPath :exec
INSERT INTO pr_state (owner, repo, number, local_path)
VALUES (?, ?, ?, ?)
ON CONFLICT (owner, repo, number) DO UPDATE SET local_path = excluded.local_path
`

type UpsertPRLocalPathParams struct {
	Owner     string
	Repo      string
	Number    int64
	LocalPath string
}

func (q *Queries) UpsertPRLocalPath(ctx context.Context, arg UpsertPRLocalPathParams) error {
	_, err := q.db.ExecContext(ctx, upsertPRLocalPath,
		arg.Owner,
		arg.Repo,
		arg.Number,
		arg.LocalPath,
	)
	return err
}
